### ISSUE TITLE
Installation errors on Windows

### ISSUE THREAD

**Issue by dmi3kno** [bwilbertz/RLightGBM#1]
Hi @bwilbertz and thank you for the package,

While installing I had the following warnings:
- comparison between signed and unsigned integer expressions
- "NOMINMAX" redefined
and one error:
- 'inet_pton' was not declared in this scope

I think it was something to do with how my Rtools is set up. I will investigate and come back with details

**Comment by bwilbertz** [comment]
Hi @dmi3kno 

Unfortunately, I have no windows machine in order to assist debugging. 

But, I think (also concluding from the long error log in the previous version of your comment) it is an problem of the R tool chain on Windows (namely mingw32) and the original LightGBM code.

Could you check, if you can build plain LightGBM using cmake and mingw32? I fear that it compiles only on VisualStudio (which cannot be used for compiling R extensions).

**Comment by dmi3kno** [comment]
Yes, I filed an issue under the original LightGBM [project](https://github.com/Microsoft/LightGBM/issues/90). It is an issue of, funnily enough for Microsoft, some functions not defined for Windows plus some improper use of `int` comparisons. I suspect that redefinition of `NOMINMAX` in one of the modules is not a problem.

Could you, please, put a warning on the title page that compilation on Windows is not tested.

**Comment by bwilbertz** [comment]
Ok, thanks. I will update the LightGBM reference in the source of the R package as soon as this is fixed upstream.

**Comment by bwilbertz** [comment]
@dmi3kno 

I've pushed a branch which builds LightGBM without network support for Windows (i.e. disabling distributed learning on multiple machines).

Can you checkout this

``` sh
git clone --recursive -b build-win-no-network https://github.com/bwilbertz/RLightGBM.git
```

and give it a try.

**Comment by dmi3kno** [comment]
@bwilbertz 

It compiled allright, thank you. 

There were changes made upstream. Can you try to pull them in. I will recompile the main branch on Windows

**Comment by guolinke** [comment]
fixed:  https://github.com/Microsoft/LightGBM/commit/68f4547bdfec8a03e8ab769a8f295275111596f2

**Comment by bwilbertz** [comment]
@guolinke thanks for fixing. I have updated the LightGBM branch pointer to rebase on latest master.

@dmi3kno would you mind trying win install again with clean checkout of master.
(it might be that we also have to add Ws2_32 and IPHLPAPI to `PKG_LIBS`...). Thanks!

**Comment by dmi3kno** [comment]
@bwilbertz Spot on. A long list of functions from `ws2_32` is reported as undefined (called from `linkers_socket.cpp` and `network.cpp`). Did not see anything from `IPHLPAPI`, but since they are referenced in `socket_wrapper.hpp` together might be a good idea to lump it there as well. Will you ping me for a new build?

**Comment by bwilbertz** [comment]
@dmi3kno I've pushed a new version with these two libraries as linker option.
Could you try with a clean checkout again? Thanks!

**Comment by dmi3kno** [comment]
Works like a charm! Thank you very much! Issue can be now closed.
