### ISSUE TITLE
HELP: invalid package 'RLightGBM_0.1.tar.gz' !!

### ISSUE THREAD

**Issue by kroscek** [bwilbertz/RLightGBM#11]
I'm using Windows 7 and RStudio. I have installed lightgbm and it's working. 

Coming to RLightGBM, i already try exactly what's written in the installation guide. THat is, by executing the following: 
library("devtools")
find_rtools()
install.packages("RLightGBM_0.1.tar.gz", type="source", repos=NULL)

The resulting error is as follows: 
> library("devtools", lib.loc="~/R/win-library/3.3")
> find_rtools()
[1] TRUE
> install.packages("RLightGBM_0.1.tar.gz", type="source", repos=NULL)
Installing package into ‘C:/Users/Allan/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning: invalid package 'RLightGBM_0.1.tar.gz'
Error: ERROR: no packages specified
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\Allan\Documents\R\win-library\3.3" "RLightGBM_0.1.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘RLightGBM_0.1.tar.gz’ had non-zero exit status

I'm confused now?

**Comment by bwilbertz** [comment]
Hi,

did you also build the package? I mean you first have to execute
```bash
git clone --recursive https://github.com/bwilbertz/RLightGBM.git

cd RLightGBM
R CMD build --no-build-vignettes pkg/RLightGBM
```

and then do the installation as above pointing to the proper location of `RLightGBM_0.1.tar.gz`.

**Comment by kroscek** [comment]
Thank you. I thought that the installation way is for Ubuntu only. My windows can install using git shell.
But there is error when tuning it using caretModel.LGBM.sparse():
[LightGBM] [Info] Construct from CSC format is not efficient

**Comment by bwilbertz** [comment]
This is log message is not an error, just an info.
