### ISSUE TITLE
examples with caret are not really working for me

### ISSUE THREAD

**Issue by andrekos** [bwilbertz/RLightGBM#12]
The two examples with caret are not really working for me, even though the example without caret works fine. In the sparse matrix case, I have this 'not efficient' running endlessly 

#fit <- train(data.frame(idx = 1:nrow(iris)), iris$Species, method = model.sparse, matrix = mat, verbosity = 0)
#[LightGBM] [Info] Construct from CSC format is not efficient
#[LightGBM] [Info] Construct from CSC format is not efficient
#[LightGBM] [Info] Construct from CSC format is not efficient
#[LightGBM] [Info] Construct from CSC format is not efficient

if I stop, no fitting has been done:
print(fit)
#Error in print(fit) : object 'fit' not found

In the other example, RStudio keeps running and when I stop and check the warnings, they are of the form: num_used_iterations exceeding number of trained trees. Reducing num_used_iterations to 67. num_used_iterations exceeding number of trained trees. Reducing num_used_iterations to 82. etc 
No fitting is done. here either. It's on Windows 10 with the latest CRAN / Github versions of caret as well as the latest R 3.4.0 (did not work with R 3.3.3 either).  Further details are available  if required.

**Comment by bwilbertz** [comment]
Hi andrekos.

Those warnings are ok. This is just an example and for sure not very efficient to run a full dense matrix (like the one from `iris`) as a sparse matrix. Just let it run and it should give comparable accuracy as for the dense matrix case.

**Comment by andrekos** [comment]
I checked it again and it worked indeed - I just expected super speeds from LightGBM on the Iris data set. I should have been a little more patient. Thanks for the work done and your reply.
