### ISSUE TITLE
Fail install the pacakge on win10

### ISSUE THREAD

**Issue by sugs01** [bwilbertz/RLightGBM#14]
> library(devtools)
> find_rtools()
[1] TRUE
> install.packages("RLightGBM_0.1.tar.gz", type="source", repos=NULL)
Installing package into ‘C:/Users/sugaos/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning: 程辑包无效. 'RLightGBM_0.1.tar.gz'
错误: 错误：没有设定程序包
Warning in install.packages :
  running command '"C:/PROGRA~1/MICROS~4/RSERVE~1/R_SERVER/bin/x64/R" CMD INSTALL -l "C:\Users\sugaos\Documents\R\win-library\3.3" "RLightGBM_0.1.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘RLightGBM_0.1.tar.gz’ had non-zero exit status
Thanks!
My computer: win10, 2cores, Mircorsoft R Server9.10

**Comment by grayskripko** [comment]
@suyi19890508
I added [a pull request](https://github.com/bwilbertz/RLightGBM/pull/13/commits/ab0fb94a9ed5683c4b0be016859836d6b77bde55) yesterday.
Try ```install.packages("RLightGBM/RLightGBM_0.1.tar.gz", type="source", repos=NULL)```

**Comment by bwilbertz** [comment]
@suyi19890508 Can you confirm, that the change propsed by  @grayskripko solves your problem?

**Comment by sugs01** [comment]
@bwilbertz No, I can't install the RLightGBM package through the code "install.packages("RLightGBM/RLightGBM_0.1.tar.gz", type="source", repos=NULL)". But I also thanks @grayskripko  to help me!

**Comment by grayskripko** [comment]
@suyi19890508 
After ```git clone``` command you must get RLightGBM folder with some content. 
Then you build RLightGBM_0.1.tar.gz archive. It will appear in RLightGBM folder
The last step for Windows will be ```install.packages(``` but you must specify the full and correct path to the archive you built. It will include RLightGBM folder because ```cd RLightGBM``` does not affect R session.

**Comment by grayskripko** [comment]
In case you ran ```git clone``` not in your current work directory (```getwd()```) the full path will be different! Just specify the full path to the RLightGBM_0.1.tar.gz archive in ```install.packages``` command
