### ISSUE TITLE
Newer lightgbm version

### ISSUE THREAD

**Issue by CaviarOnToast** [bwilbertz/RLightGBM#15]
Hi - would there be any chance RLightgbm could be updated to the latest lightgbm version? They've improved it a fair bit since, especially the latest category change.

I'd do it myself if I had any coding ability, but unfortunately far beyond me.

Regardless - thanks for writing this, it's been very useful.

**Comment by bwilbertz** [comment]
Hi,

had a look into rebasing to current LightGBM Master, but changes since my last version are massive, and lot of things got broken, so I don't know if I will quickly find time to fix this.

**Comment by CaviarOnToast** [comment]
Ahh, OK. Please don't bother on my accord if it's a hefty job - was hoping it would just be a cut and paste thing, few tweaks and voila.

**Comment by bwilbertz** [comment]
@CaviarOnToast if you are still interested, I've updated code to the latest LightGBM master.
