### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by PauleBBB** [bwilbertz/RLightGBM#16]
Hi.

I get an error message while trying to install under Windows 10:

Command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-34~1.2/etc/x64/Makeconf" -f  SHLIB="RLightGBM.dll" WIN=64 TCLBIN=64 ' resulted in  Status 2
ERROR: compilation failed for package 'RLightGBM'

I guess it is a problem with compiling via mingw_64 as I managed to install the Microsoft package version by compiling with Visual Studio. Is there a way to compile your version the same way? Or any other ideas?

Thank you for your efforts!

**Comment by bwilbertz** [comment]
Hi. 

It should be possible to compile with mingw. Can you paste the complete output?

Thanks.

**Comment by PauleBBB** [comment]
* installing to library 'C:/Program Files/R/R-3.4.2/library'
* installing *source* package 'RLightGBM' ...
** libs
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -I../inst/include -ILightGBM/include -DUSE_SOCKET -I"C:/Program Files/R/R-3.4.2/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"  -fopenmp -pthread   -O2 -Wall  -mtune=core2 -c RLightGBM.cpp -o RLightGBM.o
RLightGBM.cpp: In function 'Rcpp::NumericVector RLGBM_PredictFromMat(Rcpp::XPtr<LightGBM::Booster>, Rcpp::NumericMatrix, int, int)':
RLightGBM.cpp:134:57: error: no matching function for call to 'LightGBM::Booster::Predict(int&, int&, int, std::function<std::vector<std::pair<int, double> >(int)>&, Rcpp::traits::storage_type<14>::type*, long int*)'
                           get_row_fun, &out[0], &out_len);
                                                         ^
RLightGBM.cpp:134:57: note: candidates are:
In file included from ../inst/include/RLightGBM.h:11:0,
                 from RLightGBM.cpp:1:
LightGBM/include/LightGBM/api.hpp:82:8: note: void LightGBM::Booster::Predict(int, int, int, std::function<std::vector<std::pair<int, double> >(int)>, double*, int64_t*)
   void Predict(int num_iteration, int predict_type, int nrow,
        ^
LightGBM/include/LightGBM/api.hpp:82:8: note:   no known conversion for argument 6 from 'long int*' to 'int64_t* {aka long long int*}'
LightGBM/include/LightGBM/api.hpp:86:8: note: void LightGBM::Booster::Predict(int, int, int, std::function<std::vector<std::pair<int, double> >(int)>, const LightGBM::IOConfig&, double*, int64_t*)
   void Predict(int num_iteration, int predict_type, int nrow,
        ^
LightGBM/include/LightGBM/api.hpp:86:8: note:   candidate expects 7 arguments, 6 provided
LightGBM/include/LightGBM/api.hpp:91:8: note: void LightGBM::Booster::Predict(int, int, const char*, int, const LightGBM::IOConfig&, const char*)
   void Predict(int num_iteration, int predict_type, const char* data_filename,
        ^
LightGBM/include/LightGBM/api.hpp:91:8: note:   no known conversion for argument 4 from 'std::function<std::vector<std::pair<int, double> >(int)>' to 'int'
RLightGBM.cpp: In function 'Rcpp::NumericVector RLGBM_PredictFromCSR(Rcpp::XPtr<LightGBM::Booster>, Rcpp::IntegerVector, Rcpp::IntegerVector, Rcpp::NumericVector, Rcpp::IntegerVector, int, int)':
RLightGBM.cpp:158:57: error: no matching function for call to 'LightGBM::Booster::Predict(int&, int&, Rcpp::traits::storage_type<13>::type&, std::function<std::vector<std::pair<int, double> >(int)>&, Rcpp::traits::storage_type<14>::type*, long int*)'
                           get_row_fun, &out[0], &out_len);
                                                         ^
RLightGBM.cpp:158:57: note: candidates are:
In file included from ../inst/include/RLightGBM.h:11:0,
                 from RLightGBM.cpp:1:
LightGBM/include/LightGBM/api.hpp:82:8: note: void LightGBM::Booster::Predict(int, int, int, std::function<std::vector<std::pair<int, double> >(int)>, double*, int64_t*)
   void Predict(int num_iteration, int predict_type, int nrow,
        ^
LightGBM/include/LightGBM/api.hpp:82:8: note:   no known conversion for argument 6 from 'long int*' to 'int64_t* {aka long long int*}'
LightGBM/include/LightGBM/api.hpp:86:8: note: void LightGBM::Booster::Predict(int, int, int, std::function<std::vector<std::pair<int, double> >(int)>, const LightGBM::IOConfig&, double*, int64_t*)
   void Predict(int num_iteration, int predict_type, int nrow,
        ^
LightGBM/include/LightGBM/api.hpp:86:8: note:   candidate expects 7 arguments, 6 provided
LightGBM/include/LightGBM/api.hpp:91:8: note: void LightGBM::Booster::Predict(int, int, const char*, int, const LightGBM::IOConfig&, const char*)
   void Predict(int num_iteration, int predict_type, const char* data_filename,
        ^
LightGBM/include/LightGBM/api.hpp:91:8: note:   no known conversion for argument 4 from 'std::function<std::vector<std::pair<int, double> >(int)>' to 'int'
make: *** [RLightGBM.o] Error 1
Warnung: Ausführung von Kommando 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-34~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-34~1.2/share/make/winshlib.mk" CXX='$(CXX11) $(CXX11STD)' CXXFLAGS='$(CXX11FLAGS)' CXXPICFLAGS='$(CXX11PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX11LDFLAGS)' SHLIB_LD='$(SHLIB_CXX11LD)' SHLIB="RLightGBM.dll" WIN=64 TCLBIN=64 ' ergab Status 2
ERROR: compilation failed for package 'RLightGBM'
* removing 'C:/Program Files/R/R-3.4.2/library/RLightGBM'

**Comment by bwilbertz** [comment]
I see. I've pushed a fix [9582339](https://github.com/bwilbertz/RLightGBM/commit/95823394fcaae88ccf1f33c2847ac6285ee0172b). Can you try again and report back?

**Comment by PauleBBB** [comment]
Works now! Thx alot!
