### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by nareshshah139** [bwilbertz/RLightGBM#3]
Hey there, is it possible to include how to do a windows installation for this package?

**Comment by bwilbertz** [comment]
@dmi3kno could you write the exact command you've used for the windows install? Thanks!

**Comment by dmi3kno** [comment]
@nareshshah139,

I did the following:

> `git clone --recursive https://github.com/bwilbertz/RLightGBM.git
>
> cd RLightGBM
>
> R CMD build --no-build-vignettes pkg/RLightGBM`

and then I would switch to R and invoke discovery of Rtools (it does not get discovered from the command line, for some reason)

> `library(devtools)
>
> find_rtools()
>
> install.packages("RLightGBM_0.1.tar.gz", type="source", repos=NULL)`

**Comment by bwilbertz** [comment]
README is updated.

**Comment by linsamtw** [comment]
Warning: invalid package 'RLightGBM_0.1.tar.gz'
錯誤: ERROR: no packages specified
Warning messages:
1: 執行中命令 '"D:/MRO/R-3.3.0/bin/x64/R" CMD INSTALL -l "D:\MRO\R-3.3.0\library" "RLightGBM_0.1.tar.gz"' 已有狀態 1 
2: In install.packages("RLightGBM_0.1.tar.gz", type = "source", repos = NULL) :
  installation of package ‘RLightGBM_0.1.tar.gz’ had non-zero exit status
