### ISSUE TITLE
Could not get running on R

### ISSUE THREAD

**Issue by balajisr26** [bwilbertz/RLightGBM#4]
Hi,

My OS is windows 10 and R version is 3.3
I have downloaded RLightGBM and ran the following command:
R CMD build RLightGBM-master/pkg/RLightGBM
R CMD INSTALL RLightGBM.zip after converting tar.gz to zip file as I am in windows 10.
A folder named RLightGBM is present in my R folder \R\win-library\3.3. But in RStudio the below code library(RLightGBM) gives error:
Error in library(RLightGBM) : 
  ‘RLightGBM’ is not a valid installed package

What am I missing.Please advise.

**Comment by bwilbertz** [comment]
Please proceed like in #3

**Comment by balajisr26** [comment]
Working now. Thanks
