### ISSUE TITLE
Windows install error

### ISSUE THREAD

**Issue by datalee** [bwilbertz/RLightGBM#6]
In file included from RLightGBM.cpp:1:0:
../inst/include/RLightGBM.h:11:28: fatal error: LightGBM/api.hpp: No such file or directory
compilation terminated.
make: *** [RLightGBM.o] Error 1

**Comment by bwilbertz** [comment]
Did you clone using `--recursive`? Does your `RLightGBM` directory contain this file?

**Comment by datalee** [comment]
yes,i use.
i found the " LightGBM/api.hpp"file,but in this file" /home/lichaochao/RLightGBM/pkg/RLightGBM/src/LightGBM/include/LightGBM/api.hpp"

**Comment by datalee** [comment]
sorry, when i take it in another computer with linux env,i is ok.thanks.
