### ISSUE TITLE
installlation error

### ISSUE THREAD

**Issue by joebling** [bwilbertz/RLightGBM#7]
When I install it on Ubuntu, it shows such error:
../inst/include/RLightGBM.h:11:28: fatal error: LightGBM/api.hpp: no such that file or directory

**Comment by bwilbertz** [comment]
Did you clone using `--recursive`? Does your RLightGBM directory contain this file?

**Comment by joebling** [comment]
it works now, thanks

**Comment by bwilbertz** [comment]
Good to hear!
